// ═══════════════════════════════════════════════════════════
// Depth System — runtime perspective scaling & polygon walk areas
//
// Loads depth maps + room configs generated by tools/depth-analyzer.
// Provides per-pixel depth lookup for character scaling and
// polygon-based walkability checks.
// ═══════════════════════════════════════════════════════════

export interface DepthConfig {
  horizonY: number;
  nearY: number;
  nearScale: number;
  farScale: number;
  walkThreshold: number;
}

export interface RoomDepthConfig {
  roomId: string;
  depthConfig: DepthConfig;
  walkArea: [number, number][];
  depthMapPath: string;
}

// ── Internal caches ────────────────────────────────────────

const depthMaps = new Map<string, ImageData>();
const roomConfigs = new Map<string, RoomDepthConfig>();
const loadingPromises = new Map<string, Promise<RoomDepthConfig | null>>();

// ── Public API ─────────────────────────────────────────────

/**
 * Load room depth config + depth map. Safe to call multiple times
 * (returns cached result). Returns null if no config exists for the room.
 */
export function loadRoomDepthConfig(
  roomId: string,
): Promise<RoomDepthConfig | null> {
  if (roomConfigs.has(roomId)) {
    return Promise.resolve(roomConfigs.get(roomId)!);
  }
  if (loadingPromises.has(roomId)) {
    return loadingPromises.get(roomId)!;
  }

  const promise = (async () => {
    try {
      const res = await fetch(`${import.meta.env.BASE_URL}room-configs/${roomId}.json`);
      if (!res.ok) return null;
      const config: RoomDepthConfig = await res.json();
      roomConfigs.set(roomId, config);
      await loadDepthMapImage(roomId, config.depthMapPath);
      return config;
    } catch {
      return null;
    }
  })();

  loadingPromises.set(roomId, promise);
  return promise;
}

/**
 * Synchronously get the cached config (null if not yet loaded).
 */
export function getRoomConfig(roomId: string): RoomDepthConfig | null {
  return roomConfigs.get(roomId) ?? null;
}

/**
 * Raw depth value at normalised position (0 = far, 1 = near).
 */
export function getDepthAt(roomId: string, nx: number, ny: number): number {
  const imageData = depthMaps.get(roomId);
  if (!imageData) return 0.5;

  const px = Math.max(0, Math.min(imageData.width - 1, Math.floor(nx * imageData.width)));
  const py = Math.max(0, Math.min(imageData.height - 1, Math.floor(ny * imageData.height)));
  const idx = (py * imageData.width + px) * 4;
  return imageData.data[idx] / 255;
}

/**
 * Character scale factor at a position.
 * Uses the depth map for per-pixel accuracy; falls back to linear
 * Y-based interpolation if the depth map isn't loaded.
 */
export function getScaleAt(roomId: string, nx: number, ny: number): number {
  const config = roomConfigs.get(roomId);
  if (!config) return 1.0;

  const { nearScale, farScale, horizonY, nearY } = config.depthConfig;

  // Depth-map sampling (preferred)
  if (depthMaps.has(roomId)) {
    const depth = getDepthAt(roomId, nx, ny);
    return farScale + (nearScale - farScale) * depth;
  }

  // Linear fallback based on Y
  const t = clamp01((ny - horizonY) / (nearY - horizonY));
  return farScale + (nearScale - farScale) * t;
}

/**
 * Is the normalised position inside the walkable polygon?
 */
export function isWalkableAt(roomId: string, nx: number, ny: number): boolean {
  const config = roomConfigs.get(roomId);
  if (!config) return true; // no config → allow (fall back to rect)
  return pointInPolygon(nx, ny, config.walkArea);
}

/**
 * Clamp a target position to the nearest walkable point.
 */
export function nearestWalkablePoint(
  roomId: string,
  nx: number,
  ny: number,
): { x: number; y: number } {
  const config = roomConfigs.get(roomId);
  if (!config) return { x: nx, y: ny };
  if (pointInPolygon(nx, ny, config.walkArea)) return { x: nx, y: ny };
  return closestPointOnPolygon(nx, ny, config.walkArea);
}

/**
 * Get the walk polygon for a room (for overlay rendering in dev tools).
 */
export function getWalkPolygon(roomId: string): [number, number][] | null {
  return roomConfigs.get(roomId)?.walkArea ?? null;
}

/**
 * Check whether a depth config has been loaded for a room.
 */
export function hasDepthConfig(roomId: string): boolean {
  return roomConfigs.has(roomId);
}

/**
 * Preload depth configs for all known room IDs.
 */
export async function preloadAllDepthConfigs(
  roomIds: string[],
): Promise<void> {
  await Promise.allSettled(roomIds.map((id) => loadRoomDepthConfig(id)));
}

// ── Internal helpers ───────────────────────────────────────

async function loadDepthMapImage(
  roomId: string,
  path: string,
): Promise<void> {
  if (depthMaps.has(roomId)) return;

  return new Promise<void>((resolve) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext('2d')!;
      ctx.drawImage(img, 0, 0);
      depthMaps.set(roomId, ctx.getImageData(0, 0, img.width, img.height));
      resolve();
    };
    img.onerror = () => resolve(); // graceful fallback
    img.src = path;
  });
}

function clamp01(v: number): number {
  return Math.max(0, Math.min(1, v));
}

// ── Geometry: point-in-polygon (ray-casting) ───────────────

function pointInPolygon(
  px: number,
  py: number,
  polygon: [number, number][],
): boolean {
  let inside = false;
  const n = polygon.length;
  for (let i = 0, j = n - 1; i < n; j = i++) {
    const [xi, yi] = polygon[i];
    const [xj, yj] = polygon[j];
    if (yi > py !== yj > py && px < ((xj - xi) * (py - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

// ── Geometry: closest point on polygon boundary ────────────

function closestPointOnPolygon(
  px: number,
  py: number,
  polygon: [number, number][],
): { x: number; y: number } {
  let minDist = Infinity;
  let best = { x: px, y: py };
  const n = polygon.length;

  for (let i = 0; i < n; i++) {
    const j = (i + 1) % n;
    const cp = closestPointOnSegment(
      px, py,
      polygon[i][0], polygon[i][1],
      polygon[j][0], polygon[j][1],
    );
    const d = (cp.x - px) ** 2 + (cp.y - py) ** 2;
    if (d < minDist) {
      minDist = d;
      best = cp;
    }
  }
  return best;
}

function closestPointOnSegment(
  px: number, py: number,
  ax: number, ay: number,
  bx: number, by: number,
): { x: number; y: number } {
  const dx = bx - ax;
  const dy = by - ay;
  const lenSq = dx * dx + dy * dy;
  if (lenSq === 0) return { x: ax, y: ay };

  const t = clamp01(((px - ax) * dx + (py - ay) * dy) / lenSq);
  return { x: ax + t * dx, y: ay + t * dy };
}
