// ═══════════════════════════════════════════════════════════
// Segmentation System — loads room segmentation data
// generated by tools/depth-analyzer/segment.py
//
// Provides floor polygon, object candidates, and background
// regions for DevTools overlay rendering.
// ═══════════════════════════════════════════════════════════

export interface SegmentBBox {
  x: number; // normalized 0-1
  y: number;
  w: number;
  h: number;
}

export interface SegmentBBoxPixels {
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface ObjectSegment {
  segmentId: number;
  label: string;
  score: number;
  areaPct: number;
  bbox: SegmentBBox;
  bboxPixels: SegmentBBoxPixels | null;
  centroid: { x: number; y: number };
  meanDepth: number;
  depthContrast: number;
  confidence: number;
}

export interface BackgroundRegion {
  segmentId: number;
  label: string;
  score: number;
  areaPct: number;
  bbox: SegmentBBox | null;
  centroid: { x: number; y: number };
}

export interface RoomSegmentation {
  roomId: string;
  version: number;
  generatedAt: string;
  floorPolygon: [number, number][];
  floorMaskPath: string;
  objects: ObjectSegment[];
  backgroundRegions: BackgroundRegion[];
  stats: {
    total: number;
    floor: number;
    object: number;
    background: number;
    discarded: number;
  };
}

// ── Caches ──────────────────────────────────────────────────

const segCache = new Map<string, RoomSegmentation>();
const loadingPromises = new Map<string, Promise<RoomSegmentation | null>>();
const floorMasks = new Map<string, ImageData>();

// ── Public API ───────────────────────────────────────────────

/**
 * Load segmentation data for a room from
 * /room-configs/{roomId}_segmentation.json
 * Returns null if no file exists (graceful fallback).
 */
export function loadRoomSegmentation(
  roomId: string,
): Promise<RoomSegmentation | null> {
  if (segCache.has(roomId)) return Promise.resolve(segCache.get(roomId)!);
  if (loadingPromises.has(roomId)) return loadingPromises.get(roomId)!;

  const promise = (async () => {
    try {
      const res = await fetch(
        `${import.meta.env.BASE_URL}room-configs/${roomId}_segmentation.json`,
      );
      if (!res.ok) return null;
      const data: RoomSegmentation = await res.json();
      segCache.set(roomId, data);
      if (data.floorMaskPath) {
        loadFloorMask(roomId, data.floorMaskPath);
      }
      return data;
    } catch {
      return null;
    }
  })();

  loadingPromises.set(roomId, promise);
  return promise;
}

/**
 * Synchronously get cached segmentation (null if not loaded).
 */
export function getSegmentation(roomId: string): RoomSegmentation | null {
  return segCache.get(roomId) ?? null;
}

/**
 * Get object candidates for a room, sorted by confidence.
 */
export function getObjectCandidates(roomId: string): ObjectSegment[] {
  return segCache.get(roomId)?.objects ?? [];
}

/**
 * Get the floor polygon (normalized coords) or null.
 */
export function getFloorPolygon(
  roomId: string,
): [number, number][] | null {
  const seg = segCache.get(roomId);
  if (!seg || !seg.floorPolygon.length) return null;
  return seg.floorPolygon;
}

/**
 * Get the loaded floor mask ImageData (for canvas rendering).
 */
export function getFloorMask(roomId: string): ImageData | null {
  return floorMasks.get(roomId) ?? null;
}

/**
 * Preload segmentation for multiple rooms in parallel.
 */
export async function preloadAllSegmentation(
  roomIds: string[],
): Promise<void> {
  await Promise.allSettled(roomIds.map(loadRoomSegmentation));
}

// ── Internal ─────────────────────────────────────────────────

function loadFloorMask(roomId: string, path: string): void {
  if (floorMasks.has(roomId)) return;
  const base = import.meta.env.BASE_URL;
  const resolved =
    path.startsWith('/') && !path.startsWith('//')
      ? base + path.slice(1)
      : path;

  const img = new Image();
  img.onload = () => {
    const canvas = document.createElement('canvas');
    canvas.width = img.width;
    canvas.height = img.height;
    const ctx = canvas.getContext('2d')!;
    ctx.drawImage(img, 0, 0);
    floorMasks.set(roomId, ctx.getImageData(0, 0, img.width, img.height));
  };
  img.src = resolved;
}
